#Tutorial

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3],dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [ ]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [ ]:
# Dimension
a.ndim,b.ndim

(1, 2)

In [ ]:
# Shape
b.shape

(2, 2)

In [ ]:
# Type
a.dtype,b.dtype

(dtype('int16'), dtype('int64'))

In [ ]:
# Item Size
a.itemsize,b.itemsize

(2, 8)

In [ ]:
# Total Size
a.nbytes,b.nbytes

(6, 32)

##Accessing/Changing specific elements,rows,columns,etc



In [ ]:
a = np.array([[i*5 + j for j in range(1,6)] for i in range(1,6)])
a

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# Accessing specific element [r,c]
a[1][-2] , a[1,-2]

(14, 14)

In [ ]:
# Specific Row
a[0] , a[0,:]

(array([ 6,  7,  8,  9, 10]), array([ 6,  7,  8,  9, 10]))

In [ ]:
# Specific Column
a[:,0]

array([ 6, 11, 16, 21, 26])

In [ ]:
# Stepping the elements
a[0,::2]

array([ 6,  8, 10])

In [ ]:
a[1,4] = 20
print(a)
a[:,2] = 5
print(a)

[[ 6  7  8  9 10]
 [11 12 13 14 20]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 6  7  5  9 10]
 [11 12  5 14 20]
 [16 17  5 19 20]
 [21 22  5 24 25]
 [26 27  5 29 30]]


In [ ]:
c = np.array([[[k*100 + j*10 + i for i in range(5)] for j in range(5)] for k in range(5)])
c

array([[[  0,   1,   2,   3,   4],
        [ 10,  11,  12,  13,  14],
        [ 20,  21,  22,  23,  24],
        [ 30,  31,  32,  33,  34],
        [ 40,  41,  42,  43,  44]],

       [[100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144]],

       [[200, 201, 202, 203, 204],
        [210, 211, 212, 213, 214],
        [220, 221, 222, 223, 224],
        [230, 231, 232, 233, 234],
        [240, 241, 242, 243, 244]],

       [[300, 301, 302, 303, 304],
        [310, 311, 312, 313, 314],
        [320, 321, 322, 323, 324],
        [330, 331, 332, 333, 334],
        [340, 341, 342, 343, 344]],

       [[400, 401, 402, 403, 404],
        [410, 411, 412, 413, 414],
        [420, 421, 422, 423, 424],
        [430, 431, 432, 433, 434],
        [440, 441, 442, 443, 444]]])

In [ ]:
# c[:,1,:] = [[10 for _ in range(5)] for _ in range(5)]
c[:,1,:] = [[10 for _ in range(5)] for _ in range(5)]

In [ ]:
c

array([[[  0,   1,   2,   3,   4],
        [ 10,  10,  10,  10,  10],
        [ 20,  21,  22,  23,  24],
        [ 30,  31,  32,  33,  34],
        [ 40,  41,  42,  43,  44]],

       [[100, 101, 102, 103, 104],
        [ 10,  10,  10,  10,  10],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144]],

       [[200, 201, 202, 203, 204],
        [ 10,  10,  10,  10,  10],
        [220, 221, 222, 223, 224],
        [230, 231, 232, 233, 234],
        [240, 241, 242, 243, 244]],

       [[300, 301, 302, 303, 304],
        [ 10,  10,  10,  10,  10],
        [320, 321, 322, 323, 324],
        [330, 331, 332, 333, 334],
        [340, 341, 342, 343, 344]],

       [[400, 401, 402, 403, 404],
        [ 10,  10,  10,  10,  10],
        [420, 421, 422, 423, 424],
        [430, 431, 432, 433, 434],
        [440, 441, 442, 443, 444]]])

##Initializing Different Types of Arrays

In [ ]:
# All 0s & 1s Matrix
np.zeros(5),np.ones((2,3))

(array([0., 0., 0., 0., 0.]), array([[1., 1., 1.],
        [1., 1., 1.]]))

In [ ]:
# Full Array
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
# Full like
np.full_like(c[:3,:1,:2],4)

array([[[4, 4]],

       [[4, 4]],

       [[4, 4]]])

In [ ]:
# Random Decimal Numbers
np.random.rand(4,2,2)

array([[[0.39134229, 0.43516698],
        [0.55712103, 0.65520127]],

       [[0.1610301 , 0.7141142 ],
        [0.10040421, 0.31916483]],

       [[0.72136968, 0.38900387],
        [0.37166032, 0.72624146]],

       [[0.78573796, 0.89593332],
        [0.10344324, 0.64694082]]])

In [ ]:
np.random.random_sample(b.shape)

array([[0.6782438 , 0.39600873],
       [0.63162872, 0.836713  ]])

In [ ]:
# Random Integer Values
np.random.randint(-5,7+1,size=(5,7))

array([[-4, -3, -2, -3,  3,  4,  1],
       [ 6, -4, -4,  2,  6, -3,  0],
       [ 7, -5,  1, -5, -5,  3,  3],
       [ 7, -5, -4, -2,  4,  5,  5],
       [ 2,  2, -1, -4, -5,  5,  0]])

In [ ]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat Array
a = np.random.randint(0,10,size=(10)).reshape(5,2)
a,np.repeat(a,2,axis=1)

(array([[8, 1],
        [0, 2],
        [0, 9],
        [6, 4],
        [6, 8]]), array([[8, 8, 1, 1],
        [0, 0, 2, 2],
        [0, 0, 9, 9],
        [6, 6, 4, 4],
        [6, 6, 8, 8]]))

In [ ]:
# Shallow Copying
a = np.arange(10)
b = a
b[0] = 2
a,b

(array([2, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Deep Copying
a = np.arange(10)
b = a.copy()
b[0] = 10
a,b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9]))

Mathematics

In [ ]:
a = np.arange(10)
a,a+2,a*10,a/2,a**2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]),
 array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]))

In [ ]:
b = np.arange(10,20)
b,b+a

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28]))

In [ ]:
np.sin(a) , np.cos(a)

(array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]),
 array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
         0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026]))

## Linear Algebra

In [ ]:
# Cross Product
a = np.identity(4)
b = np.full((4,3),2)
print(f"{a}\n{b}\n{a@b}\n{np.matmul(a,b)}")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
# Determinant
a = np.random.randint(1,10,(3,3))
a,np.linalg.det(a)

(array([[2, 6, 8],
        [4, 5, 9],
        [6, 2, 9]]), -14.000000000000004)

## Statistic

In [ ]:
x = np.random.randint(1,10,(3,3))
x

array([[5, 2, 1],
       [5, 8, 8],
       [9, 7, 7]])

In [ ]:
np.min(x),np.min(x,axis=1),np.min(x,axis=0)

(1, array([1, 5, 7]), array([5, 2, 1]))

In [ ]:
np.max(x),np.max(x,axis=1),np.max(x,axis=0)

(9, array([5, 8, 9]), array([9, 8, 8]))

In [ ]:
np.sum(x),np.sum(x,axis=1),np.sum(x,axis=0)

(52, array([ 8, 21, 23]), array([19, 17, 16]))

## Reorganizing Arrays

In [ ]:
x = np.random.randint(0,10,(5,4))
y = np.random.randint(0,(1,1))
x,y

(array([[5, 8, 4, 9],
        [8, 0, 9, 7],
        [8, 5, 4, 1],
        [1, 9, 6, 2],
        [7, 2, 6, 6]]), array([0, 0]))

In [ ]:
x.reshape(10,2)

array([[5, 8],
       [4, 9],
       [8, 0],
       [9, 7],
       [8, 5],
       [4, 1],
       [1, 9],
       [6, 2],
       [7, 2],
       [6, 6]])

In [ ]:
# Vertical Stacking vectors
np.vstack([x,x])

array([[5, 8, 4, 9],
       [8, 0, 9, 7],
       [8, 5, 4, 1],
       [1, 9, 6, 2],
       [7, 2, 6, 6],
       [5, 8, 4, 9],
       [8, 0, 9, 7],
       [8, 5, 4, 1],
       [1, 9, 6, 2],
       [7, 2, 6, 6]])

In [ ]:
# Horizontal Stacking Vectors
np.hstack([x,x])

array([[5, 8, 4, 9, 5, 8, 4, 9],
       [8, 0, 9, 7, 8, 0, 9, 7],
       [8, 5, 4, 1, 8, 5, 4, 1],
       [1, 9, 6, 2, 1, 9, 6, 2],
       [7, 2, 6, 6, 7, 2, 6, 6]])

##Miscellaneous

In [ ]:
# Load Data from File
np.genfromtxt('data.txt',delimiter=',')

In [ ]:
# Boolean Masking & Advanced Indexing
x > 2

array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True, False],
       [False,  True,  True, False],
       [ True, False,  True,  True]])

In [ ]:
x[x>2]

array([5, 8, 4, 9, 8, 9, 7, 8, 5, 4, 9, 6, 7, 6, 6])

In [ ]:
x[[[0,1],[2,3]]]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([4, 7])

In [ ]:
np.all(x > 2,axis=1)

array([ True, False, False, False, False])

In [ ]:
# Boolean Operator
# ~ & |

# Numpy Exercises

In [87]:
import numpy as np

In [40]:
# Create a null vector of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
# Find Memory size of any array
np.zeros(10).nbytes , np.zeros(10).size * np.zeros(10).itemsize

(80, 80)

In [42]:
# Create a null vector of size 10 but the fifth value which is 1
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [43]:
# Create a vector with values ranging from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [44]:
# Reverse a vector
np.arange(15)[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [45]:
# Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
# indices of non-zero elements from [1,2,0,0,4,0] 
y = [1,2,0,0,4,0] 
z = np.array([1,2,0,0,4,0])
z[z != 0] , np.nonzero(y)

(array([1, 2, 4]), (array([0, 1, 4]),))

In [47]:
# Create a 3x3 identity matrix
np.identity(3) , np.eye(3)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [48]:
# Create a 3x3x3 array with random values 
np.random.random((3,3,3))

array([[[0.16225445, 0.05309884, 0.76946201],
        [0.83153041, 0.23472568, 0.0615959 ],
        [0.4960899 , 0.50255639, 0.57997065]],

       [[0.45080982, 0.04480858, 0.81195816],
        [0.53739827, 0.05495708, 0.30607726],
        [0.58502189, 0.29242471, 0.36289069]],

       [[0.4435622 , 0.41539017, 0.49193797],
        [0.66840294, 0.68980298, 0.77221914],
        [0.96176309, 0.38790355, 0.53435806]]])

In [49]:
# Create a 10x10 array with random values and find the minimum and maximum values
z = np.random.random((10,10))
z,np.max(z),np.min(z),z.max(),z.min()

(array([[0.62894133, 0.02973198, 0.4168865 , 0.79743002, 0.47333249,
         0.7932585 , 0.46118275, 0.2948718 , 0.47101011, 0.52444473],
        [0.20087271, 0.4766924 , 0.39544569, 0.79326007, 0.66575957,
         0.31579935, 0.06591165, 0.73163548, 0.68286653, 0.91039718],
        [0.88439611, 0.1091813 , 0.03995216, 0.6689883 , 0.48984257,
         0.48613365, 0.32172346, 0.91115326, 0.79726628, 0.79989913],
        [0.39914133, 0.28325116, 0.92582649, 0.48271577, 0.26669702,
         0.84390035, 0.50017952, 0.94664546, 0.49457479, 0.42655873],
        [0.53608795, 0.39040653, 0.81254248, 0.91016306, 0.02635526,
         0.52775261, 0.11807913, 0.94248007, 0.930575  , 0.87395354],
        [0.48566186, 0.28738565, 0.29047393, 0.31423014, 0.57858169,
         0.1674976 , 0.0967927 , 0.20006479, 0.44241997, 0.32941352],
        [0.66584755, 0.78172727, 0.99987005, 0.68423265, 0.09302741,
         0.54376207, 0.02699852, 0.87742307, 0.69824162, 0.51375081],
        [0.98821745, 0.5389

In [50]:
# Create a random vector of size 30 and find the mean value
z = np.random.random(30)
np.mean(z),z.mean()

(0.5632975175996239, 0.5632975175996239)

In [51]:
# Create a 2d array with 1 on the border and 0 inside
z = np.zeros((10,10))
z[:,0] = z[0,:] = z[-1,:] = z[:,-1] = 1
z

# or

z = np.zeros((10,10))
z[:,[0,-1]] = z[[0,-1],:] = 1
z

# or

z = np.ones((10,10))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [53]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
z = np.zeros((8,8))
z[::2,1::2] = 1
z[1::2,::2] = 1
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [54]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [55]:
# Create a checkerboard 8x8 matrix using the tile function
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [56]:
# Normalize a 5x5 random matrix
z = np.random.random((5,5))
(z - z.mean())/z.std()

array([[ 0.96685546, -0.93686035, -0.22819833, -1.27940728, -0.84631705],
       [-1.39826849, -1.42436181,  1.34165056, -0.8128585 ,  1.35237363],
       [-0.08101709,  0.8809939 ,  1.09398898, -0.6560536 , -0.16000251],
       [ 1.04464959, -0.81032023, -0.50484019, -0.94076791,  1.80243596],
       [ 0.13603704, -0.20200757,  1.77401846,  0.5457235 , -0.65744619]])

In [57]:
# Create a custom dtype that describes a color as four unsigned bytes
color = np.dtype([('r',np.ubyte),('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [58]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
z = np.dot(np.ones((5,3)),np.ones((3,2)))
y = np.ones((5,3)) @ np.ones((3,2))
y,z

(array([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]]), array([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]]))

In [59]:
# Given a 1D array, negate all elements which are between 3 and 8, in place
z = np.arange(11)
z[(3 < z) & (z < 8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [60]:
Z = np.random.uniform(-10,+10,10)
Z,np.where(Z > 0 , np.ceil(Z),np.floor(Z))

(array([ 7.73681365,  5.01151683,  3.80859064, -2.52554086,  8.02889754,
         7.21421748,  9.61109382, -4.10349262, -4.96708306,  9.16134676]),
 array([ 8.,  6.,  4., -3.,  9.,  8., 10., -5., -5., 10.]))

In [61]:
# How to find common values between two arrays?
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
z1,z2,np.intersect1d(z1,z2)

(array([1, 1, 3, 3, 4, 2, 6, 2, 2, 2]),
 array([6, 7, 1, 9, 3, 3, 9, 4, 4, 1]),
 array([1, 3, 4, 6]))

In [62]:
# How to find common values between two 2d arrays?
z1 = np.random.randint(0,10,16).reshape(4,4)
z2 = np.random.randint(0,10,16).reshape(4,4)
z1,z2,np.intersect1d(z1,z2)

(array([[7, 9, 1, 4],
        [2, 6, 1, 2],
        [5, 8, 4, 0],
        [3, 5, 0, 1]]), array([[7, 8, 4, 7],
        [8, 3, 9, 5],
        [8, 8, 5, 1],
        [5, 8, 2, 2]]), array([1, 2, 3, 4, 5, 7, 8, 9]))

In [63]:
# How to get the dates of yesterday, today and tomorrow?
yest = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tom = np.datetime64('today') + np.timedelta64(1)
yest,today,tom

(numpy.datetime64('2021-09-28'),
 numpy.datetime64('2021-09-29'),
 numpy.datetime64('2021-09-30'))

In [64]:
# How to get all the dates corresponding to the month of July 2016
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [65]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?
a = np.ones(3)
b = np.ones(3)
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
a

array([-1., -1., -1.])

In [66]:
# Extract the integer part of a random array of positive numbers using 4 different methods
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[4. 1. 5. 8. 2. 8. 1. 8. 2. 1.]
[4. 1. 5. 8. 2. 8. 1. 8. 2. 1.]
[4. 1. 5. 8. 2. 8. 1. 8. 2. 1.]
[4 1 5 8 2 8 1 8 2 1]
[4. 1. 5. 8. 2. 8. 1. 8. 2. 1.]


In [67]:
# Create a 5x5 matrix with row values ranging from 0 to 4 
np.zeros((5,5))+np.arange(5),np.tile(np.arange(5),(5,1))

(array([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]]), array([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]))

In [68]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded 
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [69]:
# Create a random vector of size 10 and sort it
z = np.random.random(10)
z.sort()
print(z)

[0.12822699 0.36841687 0.45518205 0.47612741 0.49105624 0.53543089
 0.81221524 0.83016131 0.8427253  0.95263552]


In [70]:
# How to sum a small array faster than np.sum?
z = np.arange(10)
np.add.reduce(z)

45

In [71]:
# Consider two random array A and B, check if they are equal
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
a,b,np.allclose(a,b),np.array_equal(a,b),np.all(a == b)

(array([0, 0, 1, 1, 0]), array([1, 1, 1, 0, 1]), False, False, False)

In [72]:
# Make an array immutable (read-only)
z = np.zeros(5)
z.flags.writeable = False
z[0] = 1

ValueError: ignored

In [73]:
# Consider a random 10x2 matrix representing cartesian coordinates, 
# convert them to polar coordinates
z = np.random.random((10,2))
x,y = z[:,0],z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
r,t

(array([0.76960825, 0.50899981, 1.1173832 , 0.43359126, 1.13236344,
        0.88245503, 0.97878107, 0.34251733, 0.40456628, 0.72905878]),
 array([0.12314857, 1.09024855, 0.75650182, 1.18592252, 0.69595416,
        0.76418231, 0.52641562, 1.44525169, 1.50613695, 1.08362719]))

In [74]:
# Create random vector of size 10 and replace the maximum value by 0
z = np.random.random(10)
z[z.argmax()] = 0
z

array([0.12597279, 0.43048154, 0.23970586, 0.79498795, 0.67597626,
       0.37772752, 0.3705191 , 0.0061278 , 0.        , 0.22692491])

In [77]:
# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 
z = np.zeros((4,5),[('x',float),('y',float)]) # Structured Array
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,4)) # Mesh Grid 
# Creates a rectangular box (abhi tak toh itana hi malum he) 
z

array([[(0.  , 0.        ), (0.25, 0.        ), (0.5 , 0.        ),
        (0.75, 0.        ), (1.  , 0.        )],
       [(0.  , 0.33333333), (0.25, 0.33333333), (0.5 , 0.33333333),
        (0.75, 0.33333333), (1.  , 0.33333333)],
       [(0.  , 0.66666667), (0.25, 0.66666667), (0.5 , 0.66666667),
        (0.75, 0.66666667), (1.  , 0.66666667)],
       [(0.  , 1.        ), (0.25, 1.        ), (0.5 , 1.        ),
        (0.75, 1.        ), (1.  , 1.        )]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [80]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
x = np.arange(8)
y = x+0.5
c = 1.0/np.subtract.outer(x,y) # Performs outer operation acc to the operations
#  similiar to outer function (xi*yj)
c , np.linalg.det(c)

(array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
         -0.18181818, -0.15384615, -0.13333333],
        [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
         -0.22222222, -0.18181818, -0.15384615],
        [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
         -0.28571429, -0.22222222, -0.18181818],
        [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
         -0.4       , -0.28571429, -0.22222222],
        [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
         -0.66666667, -0.4       , -0.28571429],
        [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
         -2.        , -0.66666667, -0.4       ],
        [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
          2.        , -2.        , -0.66666667],
        [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
          0.66666667,  2.        , -2.        ]]), 3638.163637117

In [82]:
# Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [84]:
# How to print all the values of an array?
np.set_printoptions(threshold=float("inf")) # set the number of elements to be seen
Z = np.zeros((20,20))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [86]:
# find the closest value (to a given scalar) in a vector?
z = np.arange(10)
x = np.random.uniform(0,10)
z,x , np.abs(z-x).argmin()

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 6.200511671721355, 6)

In [91]:
# Create a structured array representing a position (x,y) and a color (r,g,b)
z = np.zeros(10,[('position',[('x',float,1),
                              ('y',float,1)]),
                 ('color'   ,[('r',float,1),
                              ('g',float,1),
                              ('b',float,1)])])
z

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [95]:
# Consider a random vector with shape (100,2) representing coordinates, find point by point distances
z = np.random.random((10,2))
x,y = np.atleast_2d(z[:,0],z[:,1]) # x = z[:,0],y = z[:,1]
np.sqrt((x-x.T)**2 + (y-y.T)**2)

array([[0.        , 0.46562604, 0.13978387, ..., 0.76337694, 0.83081692,
        0.12050902],
       [0.46562604, 0.        , 0.49886081, ..., 0.52506815, 0.57152859,
        0.41358912],
       [0.13978387, 0.49886081, 0.        , ..., 0.87235642, 0.93777375,
        0.08668571],
       ...,
       [0.76337694, 0.52506815, 0.87235642, ..., 0.        , 0.06927335,
        0.79332497],
       [0.83081692, 0.57152859, 0.93777375, ..., 0.06927335, 0.        ,
        0.85777979],
       [0.12050902, 0.41358912, 0.08668571, ..., 0.79332497, 0.85777979,
        0.        ]])